### PR TITLE
fix(backend): publish approved files after pipeline update

### LINKED ISSUE #4055: Make new processed files of approved entries public after pipeline update
Currently, processed files are made public when a sequence entry that they are linked to is approved. When a pipeline is updated, it may create new files. Files associated with an approved entry should be made public when the new pipeline is switched in.

(The garbage collector #3935 will be responsible for removing unused files.)

### PR DESCRIPTION
**Pull request by chaoran-chen**
resolves #4055

When submitting processed data of an already approved entry, associated files will be made public immediately. 

### PR Checklist
- ~[ ] All necessary documentation has been adapted.~
- [x] The implemented feature is covered by appropriate, automated tests.
- [x] Any manual testing that has been done is documented (i.e. what exactly was tested?)
    - The automated tests cover the fix well.

🚀 Preview: Add `preview` label to enable

### CODE REVIEW

**Review by corneliusroemer — DISMISSED** [review]
Can you briefly explain at high level how publicness is managed for files?

Should files of old processing versions remain public after bumping of processing version? If not, and people use direct s3 links that would break the links - I guess that's a reason not to expose those direct links.

Maybe we can document the intended behavior somewhere in README or file sharing dev docs.

Have you manually tested it? If so add a short blurb pls to PR.

**Comment by chaoran-chen** [comment]
Thanks for the review, @corneliusroemer.

> @chaoran-chen backend tests failing apparently (you might be aware, just in case)

It's fixed now.

> Can you briefly explain at high level how publicness is managed for files?

A file is publicly accesible in S3 if it has the "public" tag. It is made public when (1) a sequence entry is approved which includes the file in its processed data and (2) (added in this PR) when the pipeline submits processed data for an already approved entry that includes the file.

> Should files of old processing versions remain public after bumping of processing version? If not, and people use direct s3 links that would break the links - I guess that's a reason not to expose those direct links.

The current plan is that old files will be removed. This will be implemented in #3935.

> Maybe we can document the intended behavior somewhere in README or file sharing dev docs.

We'll write up the documentation as part of #4063 (some part will be enduser facing and some admin facing).

> Have you manually tested it? If so add a short blurb pls to PR.

As already written in the PR checklist, the automated test covers the feature sufficiently in my opinion. (I wrote the test (semi-)manually...)

File: backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt [hunk 1]
```diff
@@ -615,6 +628,71 @@ class SubmitProcessedDataEndpointTest(
             )
     }
 
+    @Test
+    fun `WHEN I submit file for already approved entry THEN new file is public`() {
```
Comment (fhennig) [inline backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt:632]: The title of the test is a bit odd to me - as a user I cannot submit files for already approved entries, I have to make a revision. IMO it'd be good to mention the pipeline and pipeline version aspect. Maybe: 

```suggestion
    fun `WHEN the preprocessing pipeline submits files for already approved entries THEN new file is public`() {
```

(line might no be too long and cause lint failures)

**Review by fhennig — CHANGES_REQUESTED** [review]
Nice! I like the step by step comments. Just a few things I noted, but looks generally good.

**Review by fhennig — APPROVED** [review]
great, thanks!
