### PR TITLE
fix(website): fasta was incorrectly generated with empty segments

### LINKED ISSUE #3798: Single sample Form submission: Error when only submitting 1 segment
When submitting via the form if I only upload one segment I get an error - this is a very likely scenario and should not cause an error.

Image

### PR DESCRIPTION
**Pull request by fhennig**
resolves #3798 

preview URL:

### Summary

the frontend code for the edit and single-submit form generated FASTAs that had segment headers with no data.
This PR adds a test for this case and fixes it, so empty segments aren't added to the FASTA anymore.

### Screenshot

n/A

### PR Checklist

- [ ] All necessary documentation has been adapted.
- [x] The implemented feature is covered by appropriate, automated tests.
- [x] Any manual testing that has been done is documented (i.e. what exactly was tested?) - @anna-parker: submitted a CCHF sequence with only the L segment and the submission was successful can be seen here: https://single-segment-bug.loculus.org/seq/LOC_000PERQ.1

### CODE REVIEW

File: website/src/components/Edit/InputForm.tsx [hunk 1]
```diff
@@ -210,7 +210,16 @@ export class EditableSequences {
...
-                : sequences.map((sequence) => `>${submissionId}_${sequence.key}\n${sequence.value}`).join('\n');
+                : sequences
+                      .map((sequence) => {
+                          if (sequence.value.trim().length > 0) {
+                              return `>${submissionId}_${sequence.key}\n${sequence.value}`;
+                          } else {
+                              return null;
+                          }
+                      })
+                      .filter(Boolean)
```
Comment (anna-parker) [inline website/src/components/Edit/InputForm.tsx:221]: hmm... doesn't filter(Boolean) remove `null` from the array?

Comment (anna-parker) [reply website/src/components/Edit/InputForm.tsx:221]: ah ok this does work on a preview - so perhaps the backend sets them to `null`?

File: website/src/components/Edit/InputForm.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,24 @@
+import { describe, expect, test } from 'vitest';
+
+import { EditableSequences } from './InputForm';
+
+describe('InputForm', () => {
+    test('Empty editable sequences produces `undefined`', () => {
+        const emptyEditableSequences = EditableSequences.empty();
+        expect(emptyEditableSequences.getSequenceFasta('subId')).toBeUndefined();
```
Comment (anna-parker) [inline website/src/components/Edit/InputForm.spec.tsx:8]: Maybe outside the scope of this PR but I think it would be good to rename the `getSequenceFasta` function - in my understanding it produces fasta objects with the submissionId it is given - so `createFastaWithId` would be a better name.

Also to verify my understanding each editableSequences object only contain the contents of one sample? because this function will give all sequences in the editable sequence object the same submissionId - which I don't think we want? It might be good to rename or document that as well for maintainability.

File: website/src/components/Edit/InputForm.tsx (hunk 1 above)
Comment (anna-parker) [reply website/src/components/Edit/InputForm.tsx:221]: ah I see - it should be removed because this produces the fasta - please ignore this
