### PR TITLE
fix(website): avoid duplicated items in download url and respect choice to include old versions

### LINKED ISSUE #3626: Repetition of fields in Download URLs and we were not respecting the choice to include all old versions
Here is a download URL:

`https://lapis.pathoplexus.org/mpox/sample/details?downloadAsFile=true&downloadFileBasename=mpox_metadata_2025-02-05T0105&versionStatus=LATEST_VERSION&isRevocation=false&dataFormat=tsv&nucleotideMutations=&aminoAcidMutations=&nucleotideInsertions=&aminoAcidInsertions=&versionStatus=LATEST_VERSION&isRevocation=false`

the `versionStatus=LATEST_VERSION&isRevocation=false` appears twice! 

Also when you tick to include old versions it doesn't work

### PR DESCRIPTION
**Pull request by theosanderson**
resolves #3626

We ended up with duplicate parameters in our download URL - because they were being set both from the download form and from the original search query. Now we overwrite the original search query with whatever is in the form. It's possible that previously we were not actually respecting the form about open data - depending how LAPIS processed duplicate entries. Also we were not respecting the choice about including old versions.

preview URL: http://dupe.loculus.org (no sequences due to ingest issues currently, but you can check the download URLs)

### CODE REVIEW

File: website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ export class DownloadUrlGenerator {
         }
 
         downloadParameters.toUrlSearchParams().forEach(([name, value]) => {
-            if (value.length > 0) {
+            if (value.length && !params.has(name)) {
```
Comment (theosanderson) [inline website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts:56]: Nope, this rightly makes tests fail as it would mess up the entry of multiple accessionVersions

**Review by chaoran-chen — APPROVED** [review]
Thanks! Looks good as a hotfix.

**Review by corneliusroemer — COMMENTED** [review]
We should add at least a unit test for this

**Comment by corneliusroemer** [comment]
> It's possible that previously we were not actually respecting the form about open data - depending how LAPIS processed duplicate entries.

Could we get an answer to this question? It determines how bad the issue is here

File: website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts [hunk 2]
```diff
@@ -35,28 +35,38 @@ export class DownloadUrlGenerator {
     public generateDownloadUrl(downloadParameters: SequenceFilter, option: DownloadOption) {
         const baseUrl = `${this.lapisUrl}${getEndpoint(option.dataType)}`;
         const params = new URLSearchParams();
+        const excludedParams = new Set<string>();
 
         params.set('downloadAsFile', 'true');
         params.set('downloadFileBasename', this.generateFilename(option.dataType));
+
+        excludedParams.add(VERSION_STATUS_FIELD);
```
Comment (corneliusroemer) [inline website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts:43]: I'd probably just initialize the set immediately with these 2 params? Bit cleaner :)
