### PR TITLE
fix(backend): improve error messages for malformed TSV files with line numbers and better formatting

### LINKED ISSUE #5286: Malformed TSV throws Internal Server error - improve error message for submitters
James reported seeing this internal server error when submitting to PPX:

Image

I confirmed I see this same error when submitting his sequences to main.loculus.org

### PR DESCRIPTION
**Pull request by corneliusroemer**
Based on #5287

## Summary

Fixes malformed TSV files causing 500 Internal Server Errors. Users submitting TSV files with mixed tabs/spaces or other formatting issues now receive clear 422 error messages with line numbers instead of cryptic stack traces.

Google Chrome 2025-10-21 16 28 02

## Problem

A user reported getting "500 Internal Server Error" when submitting sequences to PPX. Investigation revealed the TSV file had mixed tabs and spaces as delimiters (quoted fields separated by spaces instead of tabs). The backend threw an unhandled `CSVException: Invalid character between encapsulated token and delimiter` which resulted in a 500 error.

Example problematic TSV:
```tsv
"id"	"sampleCollectionDate"	"geoLocCountry"			"Host"  "authors"
123	2025-01-01	Switzerland  Homo Sapiens  Potter, H;
```

## Solution

Added comprehensive error handling for `CSVException` at both initialization and iteration stages, with improved error messages that include:
- Line numbers for validation errors
- Clean row value formatting (removed verbose CSVRecord debug output)
- Descriptive causes for TSV parsing failures
- Proper grammar and quoted field names

## Key Changes

**Error Handling:**
- Catch `CSVException` during CSV parser initialization
- Catch `UncheckedIOException` (which wraps `CSVException`) during lazy iteration
- Return 422 Unprocessable Entity instead of 500 Internal Server Error

**Error Messages:**
- Added line numbers: "Row at line 2 in the metadata file..."
- Centralized TSV format error message in `invalidTsvFormatException()` helper
- Improved formatting: Show row as `['field1', 'field2']` instead of `CSVRecord [comment='null', recordNumber=1, values=[...]]`
- For whitespace errors: Show only the problematic value, not the entire row
- Fixed grammar (added missing articles, quoted field names)

**Test Coverage:**
- Unit tests for malformed TSV scenarios (quoted fields with spaces, mixed delimiters, iteration errors with 1000+ rows)
- Line number verification tests for both submit and revision endpoints
- Integration test verifying CLI error handling

## Example Error Messages

**Before:**
```
500 Internal Server Error
Invalid character between encapsulated token and delimiter at line: 1, position: 55
```

**After:**
```
422 Unprocessable Entity
The metadata file is not a valid TSV file. Common causes include: fields not separated by tabs, 
improperly formatted quoted fields, inconsistent number of fields per row, or empty lines.
```

```
Row at line 2 in the metadata file contains no value for 'id'. Row: ['', 'someValue']
```

```
Row at line 3 in the metadata file: the value for 'submissionId' contains whitespace: 'foo bar'
```

Fixes #5286

🚀 Preview: https://fix-malformed-tsv-error-m.loculus.org

### CODE REVIEW

File: backend/src/main/kotlin/org/loculus/backend/utils/MetadataEntry.kt [hunk 1]
```diff
@@ -29,42 +36,65 @@ fun findAndValidateSubmissionIdHeader(headerNames: List<String>): String {
...
-            )
+    return sequence {
+        try {
+            csvParser.asSequence().withIndex().forEach { (index, record) ->
+                val recordNumber = index + 1 // First data record is #1 (header not counted)
+                val submissionId = record[submissionIdHeader]
+                if (submissionId.isNullOrEmpty()) {
+                    val rowValues = record.toList().joinToString("', '", prefix = "['", postfix = "']")
+                    throw UnprocessableEntityException(
+                        "Record #$recordNumber in the metadata file contains no value for '$submissionIdHeader'. Row: $rowValues",
```
Comment (theosanderson) [inline backend/src/main/kotlin/org/loculus/backend/utils/MetadataEntry.kt]: Thanks for the changes - I expect this might often be too long? we could truncate? Not blocking we can iterate later if you prefer

Comment (theosanderson) [reply backend/src/main/kotlin/org/loculus/backend/utils/MetadataEntry.kt]: Very long error messages do not fit on the screen and the beginning (which has the important stuff) goes off the screen iirc
