### PR TITLE
fix(backend): handle error edge cases correctly in file endpoints

### LINKED ISSUE #4602: Passing invalid group ID as superuser to /files/request-upload causes Internal server error
```
 curl -s -D - -w "%{http_code}" 'https://backend-main.loculus.org/files/request-upload?groupId=0&numberFiles=1' \
  -X 'POST' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'authorization: Bearer <REDACTED>' \

HTTP/2 500
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-type: application/json
date: Thu, 03 Jul 2025 20:50:53 GMT
expires: 0
pragma: no-cache
strict-transport-security: max-age=31536000 ; includeSubDomains
vary: Accept-Encoding
vary: origin,access-control-request-method,access-control-request-headers,accept-encoding
x-content-type-options: nosniff
x-frame-options: DENY
x-request-id: 7ac1e7b4-b504-4225-ab01-964a2efdb518
x-robots-tag: noindex, nofollow
x-xss-protection: 0

{"type":"about:blank","title":"Internal Server Error","status":500,"detail":"org.postgresql.util.PSQLException: ERROR: insert or update on table \"files\" violates foreign key constraint \"files_group_id_fkey\"\n  Detail: Key (group_id)=(0) is not present in table \"groups_table\".","instance":"/files/request-upload"}
```

Other ideas for potential bugs: 0 or negative number of files. Very high number of files. Non-integer for both fields.

### PR DESCRIPTION
**Pull request by corneliusroemer**
resolves #4602

- if user isn't authenticated throw Unauthorized not Forbidden
- check group exists before executing sql
- validate number of files that were requested can't be < 1
- include 'WWW-Authenticate: Bearer' header for 401/403 per spec
- fix grammar in error message where single group can exist

🚀 Preview: Add `preview` label to enable

### CODE REVIEW

File: backend/src/main/kotlin/org/loculus/backend/controller/ExceptionHandler.kt [hunk 1]
```diff
@@ -45,21 +43,19 @@ class ExceptionHandler : ResponseEntityExceptionHandler() {
         )
     }
 
-    @ExceptionHandler(DummyUnauthorizedExceptionToMakeItAppearInSwaggerUi::class)
```
Comment (anna-parker) [inline backend/src/main/kotlin/org/loculus/backend/controller/ExceptionHandler.kt:48]: oh interesting - this function apparently is not actually used at runtime and will only show up in the swaggerUI

File: backend/src/test/kotlin/org/loculus/backend/controller/files/GetFilesEndpointTest.kt [hunk 2]
```diff
@@ -38,7 +38,7 @@ class GetFilesEndpointTest(
         )
 
         filesClient.getFile(data.accession, data.version, "myFileCategory", "hello.txt")
-            .andExpect(status().isForbidden())
+            .andExpect(status().isUnauthorized())
```
Comment (anna-parker) [inline backend/src/test/kotlin/org/loculus/backend/controller/files/GetFilesEndpointTest.kt:41]: do we have a test for the Forbidden case?

File: backend/src/main/kotlin/org/loculus/backend/controller/ExceptionHandler.kt [hunk 3]
```diff
@@ -104,10 +100,15 @@ class ExceptionHandler : ResponseEntityExceptionHandler() {
     fun handleForbiddenException(e: ForbiddenException): ResponseEntity<ProblemDetail> {
         log.info { "Caught forbidden exception: ${e.message}" }
 
-        return responseEntity(
-            HttpStatus.FORBIDDEN,
-            e.message,
-        )
+        return ResponseEntity.status(HttpStatus.FORBIDDEN)
```
[the remark this answers is not in the document]
Comment (corneliusroemer) [reply backend/src/main/kotlin/org/loculus/backend/controller/ExceptionHandler.kt:103]: indeed :D

File: backend/src/test/kotlin/org/loculus/backend/controller/files/GetFilesEndpointTest.kt (hunk 2 above)
Comment (corneliusroemer) [reply backend/src/test/kotlin/org/loculus/backend/controller/files/GetFilesEndpointTest.kt:41]: I don't know - but the error code was wrong so this just fixes that
