### PR TITLE
fix(website): disable search autocomplete fields until hydration completes

### LINKED ISSUE #5096: Flaky integration test: `[chromium-with-dep] › search.dependent.spec.ts:12:9 › Search › search form resets when the reset button is clicked `
```
1) [chromium-with-dep] › tests/specs/features/search/search.dependent.spec.ts:12:9 › Search › search form resets when the reset button is clicked 

    TimeoutError: locator.click: Timeout 3000ms exceeded.
    Call log:
      - waiting for getByRole('option').first()


       at pages/search.page.ts:34

      32 |         await this.page.waitForTimeout(500);
      33 |
    > 34 |         await this.page.getByRole('option').first().click({ timeout: 3000 });
         |                                                     ^
      35 |
      36 |         await this.page.keyboard.press('Escape');
      37 |         await this.page.waitForTimeout(200);
        at SearchPage.select (/home/runner/work/loculus/loculus/integration-tests/tests/pages/search.page.ts:34:53)
        at /home/runner/work/loculus/loculus/integration-tests/tests/specs/features/search/search.dependent.spec.ts:15:9

    Error Context: test-results/specs-features-search-sear-900d2-the-reset-button-is-clicked-chromium-with-dep/error-context.md

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    TimeoutError: locator.click: Timeout 3000ms exceeded.
    Call log:
      - waiting for getByRole('option').first()


       at pages/search.page.ts:34

      32 |         await this.page.waitForTimeout(500);
      33 |
    > 34 |         await this.page.getByRole('option').first().click({ timeout: 3000 });
         |                                                     ^
      35 |
      36 |         await this.page.keyboard.press('Escape');
      37 |         await this.page.waitForTimeout(200);
        at SearchPage.select (/home/runner/work/loculus/loculus/integration-tests/tests/pages/search.page.ts:34:53)
        at /home/runner/work/loculus/loculus/integration-tests/tests/specs/features/search/search.dependent.spec.ts:15:9

    Error Context: test-results/specs-features-search-sear-900d2-the-reset-button-is-clicked-chromium-with-dep-retry1/error-context.md

    attachment #2: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/specs-features-search-sear-900d2-the-reset-button-is-clicked-chromium-with-dep-retry1/trace.zip
    Usage:

        npx playwright show-trace test-results/specs-features-search-sear-900d2-the-reset-button-is-clicked-chromium-with-dep-retry1/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

    Retry #2 ───────────────────────────────────────────────────────────────────────────────────────

    TimeoutError: locator.click: Timeout 3000ms exceeded.
    Call log:
      - waiting for getByRole('option').first()


       at pages/search.page.ts:34

      32 |         await this.page.waitForTimeout(500);
      33 |
    > 34 |         await this.page.getByRole('option').first().click({ timeout: 3000 });
         |                                                     ^
      35 |
      36 |         await this.page.keyboard.press('Escape');
      37 |         await this.page.waitForTimeout(200);
        at SearchPage.select (/home/runner/work/loculus/loculus/integration-tests/tests/pages/search.page.ts:34:53)
        at /home/runner/work/loculus/loculus/integration-tests/tests/specs/features/search/search.dependent.spec.ts:15:9

    Error Context: test-results/specs-features-search-sear-900d2-the-reset-button-is-clicked-chromium-with-dep-retry2/error-context.md

  1 failed
    [chromium-with-dep] › tests/specs/features/search/search.dependent.spec.ts:12:9 › Search › search form resets when the reset button is clicked 
```

### PR DESCRIPTION
**Pull request by corneliusroemer**
Resolves #5096

Reviewable diff (prior to npm run format changing indentation): https://github.com/loculus-project/loculus/compare/c819683afe5f2b489e3b2ec510b2a55ba78d8737...4b57542e368e524614cd0d36a284ddf3dfb884ef

## Summary

At least one flaky test was due to incorrect disabling of server-rendered UI. Previously we handled this by wrapping the to-be-disabled element with `<DisabledUntilHydration>`. That only worked when the to-be-disabled element was the direct child and hence brittle.

It's error prone and increases nesting to use `<DisabledUntilHydration>`. This PR switches to a wrapper pattern where we wrap the to-be-disabled element with the hydration logic and then reexport it. To disable until hydration, all that has to be changed is the import.

This is more elegant and also allows CI linting for use of forbidden imports (in the future we can forbid importing the unhydration-disabled import to prevent new and old devs falling into the same trap).

For the native `<button>` element, we need to change casing to `<Button>` - otherwise the same pattern works.

The diff is unfortunately very large due to changing indentation - nothing else should change. In fact that might be a good test to run: reinsert empty divs to see if the diff is smaller - than removing the empty diffs again post-merge.

<details>

<summary>Claude description below</summary>

## Approach

Instead of manually wrapping components with `DisabledUntilHydrated` or calling `useClientFlag` in each component, we now use wrapper components that:

1. **Automatically integrate hydration detection** - Uses `useClientFlag` internally
2. **Disable until client-ready** - Passes `disabled` prop to underlying components
3. **Maintain the same API** - Drop-in replacements for native Headless UI components

### New Wrapper Components

**`src/components/common/headlessui/Combobox.tsx`**
- Wraps Headless UI `Combobox` component
- Automatically disables until hydration via `useClientFlag`
- Re-exports all Combobox subcomponents unchanged

**`src/components/common/Button.tsx`**
- Wraps native `<button>` element
- Automatically disables until hydration via `useClientFlag`
- Supports `alsoDisabledIf` prop for additional disable conditions

### Updated Components

**Combobox wrapper usage (4 components):**
- `SingleChoiceAutoCompleteField.tsx` - Removed manual `useClientFlag` + `disabled` prop
- `MultiChoiceAutoCompleteField.tsx` - Removed manual `useClientFlag` + `disabled` prop
- `InputField.tsx` - Replaced `DisabledUntilHydrated` wrapper with import change
- `MutationField.tsx` - Replaced `DisabledUntilHydrated` wrapper with import change

**Button wrapper usage (5 components, 11 total buttons):**
- `SearchForm.tsx` - 3 buttons
- `GroupPage.tsx` - 3 buttons
- `DataUploadForm.tsx` - 1 button (with `alsoDisabledIf={isPending}`)
- `SeqSetItemActions.tsx` - 3 buttons
- `GroupForm.tsx` - 1 button

## Scope

**Important:** This PR only adds wrappers for components that **already had** hydration protection via `DisabledUntilHydrated` or `useClientFlag`. No new hydration protection is being added to components that didn't have it before.

## Root Cause

The original issue was that `DisabledUntilHydrated` wrapped outer divs, but Headless UI components don't inherit disabled state from parent divs. The `disabled` prop must be passed directly to the Headless UI component itself.

</details>

🚀 Preview: https://deflake-search-combobox.loculus.org

### CODE REVIEW

**Comment by corneliusroemer** [comment]
## Future Refactoring: Wrapper Component Pattern

The current fix uses `useClientFlag` + `disabled` prop directly. A more maintainable approach would be creating wrapper components (facade pattern) that encapsulate hydration protection.

### Components that could benefit from wrappers:

**Combobox** (4 usages):
- `src/components/SearchPage/fields/SingleChoiceAutoCompleteField.tsx` - This PR (useClientFlag)
- `src/components/SearchPage/fields/MultiChoiceAutoCompleteField.tsx` - This PR (useClientFlag)
- `src/components/SearchPage/fields/MutationField.tsx:60` - DisabledUntilHydrated wrapper (won't work)
- `src/components/Edit/InputField.tsx:32` - DisabledUntilHydrated wrapper (won't work)

**Listbox** (1 usage):
- `src/components/Submission/FileUpload/ColumnMappingModal.tsx` - No protection

**Menu** (4 usages):
- `src/components/ReviewPage/ReviewPage.tsx`
- `src/components/SearchPage/DownloadDialog/LinkOutMenu.tsx`
- `src/components/Navigation/OrganismNavigation.tsx`
- `src/components/SequenceDetailsPage/LinkWithMenuComponent.tsx`

**Disclosure** (1 usage):
- `src/components/Navigation/DocsMenu.tsx`

### Enforcement via CI

Could enforce usage of wrappers with ESLint's `no-restricted-imports`:

```js
// .eslintrc
{
  "rules": {
    "no-restricted-imports": ["error", {
      "paths": [{
        "name": "@headlessui/react",
        "importNames": ["Combobox", "Listbox", "Menu", "Disclosure"],
        "message": "Import from src/components/common/HeadlessUI instead for hydration safety"
      }]
    }]
  }
}
```

This would fail CI if anyone imports the raw Headless UI components directly.

File: website/src/components/SearchPage/fields/MutationField.tsx [hunk 1]
```diff
@@ -57,7 +57,7 @@ export const MutationField: FC<MutationFieldProps> = ({ suborganismSegmentAndGen
 
     return (
         <div className='flex relative mb-2 flex-row w-full'>
-            <DisabledUntilHydrated>
+            <>
```
Comment (theosanderson) [inline website/src/components/SearchPage/fields/MutationField.tsx]:
```suggestion
```

File: website/src/components/common/Button.tsx
Comment (theosanderson) [inline website/src/components/common/Button.tsx]: Can we use `<DisabledUntilHydrated>` here?

File: website/src/components/common/headlessui/Combobox.tsx
[the remark this answers is not in the document]
Comment (theosanderson) [reply website/src/components/common/headlessui/Combobox.tsx]: I meant the component..
