### PR TITLE
fix(backend,ingest): handle revoked sequences in /get-original-metadata, they have null metadata

### LINKED ISSUE #4036: Ingest error if sequence is revoked
I just noticed that if I revoke a sequence that was ingested by INSDC this breaks (re)ingest - I confirmed this is also true on main:

```
5:20:11    ERROR call_loculus.py:get-submitted - Error decoding JSON from /get-original-metadata: {"accession":"LOC_000005Q","version":1,"submitter"
[..]
a.util.Map.get(Object)" because "metadata" is null
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/jsonlines/jsonlines.py", line 326, in read
    value: JSONValue = self._loads(line)
                       ^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/package/scripts/call_loculus.py", line 456, in get_submitted
    entries = list(jsonlines.Reader(response.iter_lines()).iter())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/jsonlines/jsonlines.py", line 434, in iter
    yield self.read(
          ^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/jsonlines/jsonlines.py", line 331, in read
    raise exc from orig_exc
jsonlines.jsonlines.InvalidLineError: line contains invalid json: unexpected character: line 1 column 1 (char 0) (line 167)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/package/scripts/call_loculus.py", line 645, in <module>
    submit_to_loculus()
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/scripts/call_loculus.py", line 640, in submit_to_loculus
    response = get_submitted(config)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/package/scripts/call_loculus.py", line 463, in get_submitted
    raise ValueError from err
ValueError
```

### PR DESCRIPTION
**Pull request by corneliusroemer**
resolves #4036 

co-authored by @anna-parker

Fix backend to deal with `null` original metadata.

Now we get this for revoked sequences in `/get-original-metadata` (we add the `isRevocation` field to the output):

```
{"accession":"LOC_000M2HN","version":2,"submitter":"superuser","originalMetadata":null, "isRevocation": True}
```

Ingest also works: we remove the key sort and additionally handle revocations separately (as they do not contain the INSDC accession in the originalMetadata as it is empty) 

We now emit isRevocation in `/get-original-metadata` to allow ingest to handle revocations properly.

### Testing

- Unit test added that reproduces the bug and no longer does so with the fix
- Manual in preview: Revoke a sequence, rerun ingest without problems
- Manual in preview: Revoke two sequences, rerun ingest without problems (Anya noticed this failed and she fixed it)

### Ideas for future

- Nice to have: Integration test for reingest with a revoked sequence

### PR Checklist
- ~[ ] All necessary documentation has been adapted.~
- [x] The implemented feature is covered by appropriate, automated tests.
- [x] Any manual testing that has been done is documented (i.e. what exactly was tested?)

🚀 Preview: https://fix-null-metadata.loculus.org

### CODE REVIEW

**Comment by corneliusroemer** [comment]
The backend fix seems to work, but now ingest is still broken:

```
[Tue Apr 22 17:26:12 2025]
localrule get_previous_submissions:
    input: scripts/call_loculus.py, results/metadata_post_prepare.ndjson, results/config.yaml
    output: results/previous_submissions.json
    jobid: 12
    reason: Missing output files: results/previous_submissions.json; Input files updated by another job: results/metadata_post_prepare.ndjson
    resources: tmpdir=/tmp
        sleep 0
        python scripts/call_loculus.py             --mode get-submitted             --config-file results/config.yaml             --log-level DEBUG             --output results/previous_submissions.json
17:26:13     INFO call_loculus.py:get-submitted - Config: Config(organism='ebola-sudan', backend_url='https://backend-fix-null-metadata.loculus.org', keycloak_token_url='http://loculus-keycloak-service:8083/realms/loculus/protocol/openid-connect/token', keycloak_client_id='backend-client', username='insdc_ingest_user', password='insdc_ingest_user', group_name='insdc_ingest_group', nucleotide_sequences=['main'], segmented=False, batch_chunk_size=10000)
17:26:13     INFO call_loculus.py:get-submitted - Getting submitted sequences
17:26:13     INFO call_loculus.py:get-submitted - Getting previously submitted sequences
17:26:13     INFO call_loculus.py:get-submitted - Backend has status of: 166 sequence entries from ingest
17:26:13     INFO call_loculus.py:get-submitted - Ingest has submitted: 167 sequence entries to ingest
17:26:13     INFO call_loculus.py:get-submitted - Got info on 167 previously submitted sequences/accessions
Traceback (most recent call last):
  File "/package/scripts/call_loculus.py", line 645, in <module>
    submit_to_loculus()
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/scripts/call_loculus.py", line 641, in submit_to_loculus
    Path(output).write_text(json.dumps(response, indent=4, sort_keys=True), encoding="utf-8")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/conda/lib/python3.12/json/encoder.py", line 354, in _iterencode_dict
    items = sorted(dct.items())
            ^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by corneliusroemer** [comment]
Test successfully fails pre-PR, and passes post-PR:

Pre-failure:
```
> Task :test

GetOriginalMetadataEndpointTest > GIVEN revoked sequences exist THEN endpoint does not throw exception() FAILED
    java.lang.RuntimeException: Failed to parse line: An unexpected error occurred while streaming, aborting the stream: Parameter specified as non-null is null: method org.loculus.backend.api.AccessionVersionOriginalMetadata.<init>, parameter originalMetadata
        at org.loculus.backend.controller.submission.GetOriginalMetadataEndpointTest.GIVEN revoked sequences exist THEN endpoint does not throw exception(GetOriginalMetadataEndpointTest.kt:402)

        Caused by:
        com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'An': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         at [Source: UNKNOWN; line: 1, column: 3]
            at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2584)
            at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2610)
            at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2618)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:825)
            at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3017)
            at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2051)
            at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:780)
            at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:5004)
            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4910)
            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3860)
            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3843)
            at org.loculus.backend.controller.submission.GetOriginalMetadataEndpointTest.GIVEN revoked sequences exist THEN endpoint does not throw exception(GetOriginalMetadataEndpointTest.kt:399)
```

File: backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt [hunk 1]
```diff
@@ -189,4 +188,14 @@ class GetOriginalMetadataEndpointTest(
         submissionControllerClient.getOriginalMetadata()
             .andExpect(status().isOk)
     }
+
+    // Regression test for https://github.com/loculus-project/loculus/issues/4036
```
Comment (chaoran-chen) [inline backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt:192]:
```suggestion
```

I'd actually prefer not to document this (the test generally makes sense in my opinion, no need to explain the reason).

**Review by chaoran-chen — APPROVED** [review]
Nice, thank you, @corneliusroemer!

File: backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt (hunk 1 above)
Comment (corneliusroemer) [reply backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt:192]: Hmm, why not explain the reason? It's useful context, established projects I've seen often link to issues for further context, e.g. https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/cast_alignment.rs#L45

Comment (chaoran-chen) [reply backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt:192]: In this case, I don't feel that it is very useful information. If one would like to learn about the background/history of a change, one can look up the git history. Also, it's not something that we've been doing otherwise and it seems inconsistent. But it's not a big deal, feel free to keep it if you like :)

File: backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt [hunk 2]
```diff
@@ -1080,8 +1081,10 @@ class SubmissionDatabaseService(
             .fetchSize(streamBatchSize)
             .asSequence()
             .map {
-                val metadata = it[originalMetadata]
-                val selectedMetadata = fields?.associateWith { field -> metadata[field] }
+                // Revoked sequences have no original metdadata, hence null can happen
+                @Suppress("USELESS_ELVIS")
```
Comment (anna-parker) [inline backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt:1085]: oh wow that is weirdest suppress argument, I thought it was a mistake initially!

**Comment by anna-parker** [comment]
Oh so annoying if we revoke 2 sequences ingest gives us another error:

```
06:53:13    ERROR call_loculus.py:get-submitted - INSDC accession None has multiple loculus accessions: LOC_000M1DY and LOC_000M2HN!
Traceback (most recent call last):
  File "/package/scripts/call_loculus.py", line 645, in <module>
    submit_to_loculus()
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/package/scripts/call_loculus.py", line 640, in submit_to_loculus
    response = get_submitted(config)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/package/scripts/call_loculus.py", line 517, in get_submitted
    raise ValueError(message)
ValueError: INSDC accession None has multiple loculus accessions: LOC_000M1DY and LOC_000M2HN!
```
this is (I believe because we take the latest version of a loculus accession and from that grab the INSDC accession from the original metadata which is now `null`...

**Comment by corneliusroemer** [comment]
We should do another manual test of 2 revocations + reingest to see if this now works, maybe even 3 revocations :)

File: ingest/scripts/call_loculus.py [hunk 3]
```diff
@@ -525,6 +538,27 @@ def get_submitted(config: Config):
                     "submitter": submitter,
                 }
             )
+    # Ensure revocations added to correct INSDC accession
+    for loculus_accession, insdc_accessions in loculus_to_insdc_accession_map.items():
+        if loculus_accession in revocation_dict:
+            for insdc_accession in insdc_accessions:
+                logger.info(f"revocation dict {revocation_dict}")
```
Comment (anna-parker) [inline ingest/scripts/call_loculus.py:545]: oh wupps lets remove this line
```suggestion
```

**Review by anna-parker — APPROVED** [review]
